import React from 'react'

const About = () => {
    return (
        <div>
            <h1>About page</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis aliquam iure quo nam optio facere placeat, ut velit cumque delectus fuga, assumenda veritatis dolores voluptatem vero dolor natus beatae, animi adipisci. Deleniti a magni ullam iste repudiandae rem veniam aliquid nemo eum! Id dolor nihil, voluptas ipsam iste illo ex molestias, libero sequi pariatur quae, architecto expedita nemo. Vero accusantium, amet aspernatur cumque consequuntur doloremque recusandae, in eaque tenetur fuga eligendi. Illum, fugit voluptatum a, odit suscipit cum corporis commodi quo magni nostrum alias sint porro consequuntur iusto aperiam adipisci eveniet pariatur. Praesentium saepe culpa veniam accusantium laudantium cupiditate nostrum soluta necessitatibus mollitia omnis debitis, nisi recusandae dolorem, et pariatur quam atque molestias sunt nam amet ab! Tempora quaerat voluptates praesentium illo blanditiis et totam, dolor impedit, repellendus magni porro perspiciatis aut ut. Sed recusandae ad quos quas id qui nulla inventore quidem, quae unde quo excepturi in, at eius nihil aliquam assumenda omnis! Itaque labore eligendi placeat sed, voluptates vitae ipsa mollitia. Voluptas aliquid distinctio assumenda ratione, eum autem doloribus fugit, sit placeat nam officia tempore dolorem nostrum molestiae aut veniam rerum ducimus. Vero quod a, corrupti, deleniti suscipit facere, dignissimos dolores error amet ut neque fugit. Ducimus delectus tempora, id accusantium laboriosam laudantium sequi nulla nemo ipsam vel consectetur sunt ut autem ea, esse praesentium consequuntur distinctio, aliquam omnis a accusamus eum. Veritatis labore quibusdam nemo ipsam eaque commodi quod recusandae. Excepturi voluptatibus amet dignissimos rerum? Praesentium quae repellat, repudiandae illo ab placeat ducimus nisi iusto ex! Fugiat dicta necessitatibus autem ullam magni qui rerum earum voluptates, nihil blanditiis quis alias amet non expedita omnis modi debitis ipsa deserunt consectetur delectus vel adipisci? Quo ipsum ut doloribus accusantium. Pariatur, rerum optio inventore incidunt sint praesentium! Ex blanditiis quos soluta consequatur eius. Nulla libero placeat sed sequi. Fugiat quas nostrum est in officia harum distinctio labore sit aut exercitationem nobis, totam corporis explicabo facere numquam, ea, blanditiis nam ad nisi consequatur dolorem? Consectetur perferendis molestias, eaque voluptatum sequi veritatis iure similique unde aut excepturi quisquam, quod quasi odio animi. Id autem illum earum ut totam? Dolorem magnam sint nisi obcaecati commodi veniam delectus repellat? Voluptas dolorem optio tempora, earum sit, numquam aliquid quam accusantium adipisci dolores error, quibusdam in aut ab sequi deleniti ullam ipsum at excepturi! At sapiente atque repellat, iste, tempora sit dicta quae ut culpa harum velit, reiciendis ullam. Officia assumenda libero error sequi, odit adipisci!</p>
            <h1 className='text-[#133236] text-3xl'>Home page</h1>
        </div>
    )
}

export default About
